#!/bin/sh
# Copyright Philipp Wuensche

# Script for running by cron, every 5min should be enough

date=`date -v -0d "+%Y%m%d%H%M%S"`

usage='Usage: zfs-tm -f <configfile>'

while getopts :f: arg; do
 case ${arg} in
  f) zfs_tm_conf=$OPTARG;;
  *) echo $usage && exit
 esac
done

[ -f "${zfs_tm_conf}" ] && . "${zfs_tm_conf}"
[ "${zfs_tm_conf}" = "" ] && echo $usage && exit
[ "${my_zfs}" = "" ] && echo $usage && exit

zfs_name=`zfs list -H -o name ${my_zfs} 2> /dev/null`

if [ "$zfs_name" = "$my_zfs" ]; then
   /sbin/zfs snapshot -r ${my_zfs}@${date}
fi 
