#!/bin/sh
# Copyright Philipp Wuensche

# Script for running by cron, every 5min should be enough

date=`date -v -0d "+%Y%m%d%H%M%S"`

usage='Usage: zfs-tm-localsnapshot -f <configfile>'

while getopts :f: arg; do
 case ${arg} in
  f) zfs_tm_conf=$OPTARG;;
  *) echo $usage && exit
 esac
done

[ -f "${zfs_tm_conf}" ] && . "${zfs_tm_conf}"
[ "${zfs_tm_conf}" = "" ] && echo $usage && exit
[ "${my_zfs}" = "" ] && echo $usage && exit
[ "${my_zfstm_user}" = "" ] && echo $usage && exit

if [ ! "$my_zfstm_user" = `id -nu` ]; then
   echo "ERROR: Not running as the right backup user"
   exit
fi

zfs_name=`zfs list -H -o name ${my_zfs} 2> /dev/null`

calc_bytesize () {
  current_snapshotsize=`zfs list -H -o used ${my_zfs}|tr GMKBWX gmkbwx|sed -Ees:g:km:g -es:m:kk:g -es:k:"*2b":g -es:b:"*128w":g -es:w:"*4 ":g -e"s:(^|[^0-9])0x:\1\0X:g" -ey:x:"*":|bc |sed "s:\.[0-9]*$::g"`
}

if [ "$zfs_name" = "$my_zfs" ]; then
  /sbin/zfs snapshot -r ${my_zfs}@${date}

  if [ "${local_snapshotsize_limit}" ]; then
    _local_snapshotsize_limit=`echo "${local_snapshotsize_limit}"|tr GMKBWX gmkbwx|sed -Ees:g:km:g -es:m:kk:g -es:k:"*2b":g -es:b:"*128w":g -es:w:"*4 ":g -e"s:(^|[^0-9])0x:\1\0X:g" -ey:x:"*":|bc |sed "s:\.[0-9]*$::g"`

    calc_bytesize

    while [ "$current_snapshotsize" -gt "$_local_snapshotsize_limit" ]; do
      _delete=`zfs list -H -o name -t snapshot -r ${my_zfs} | grep ${my_zfs}'@' | head -n1`
      /sbin/zfs destroy ${_delete}
      calc_bytesize
    done
  fi
fi
