#!/bin/sh
# Copyright Philipp Wuensche

# Script for running by cron, every 5min should be enough

date=`date -v -0d "+%Y%m%d%H%M%S"`

usage='Usage: zfs-tm-localsnapshot -f <configfile>'

while getopts :f: arg; do
 case ${arg} in
  f) zfs_tm_conf=$OPTARG;;
  *) echo $usage && exit
 esac
done

[ -f "${zfs_tm_conf}" ] && . "${zfs_tm_conf}"
[ "${zfs_tm_conf}" = "" ] && echo $usage && exit
[ "${my_zfs}" = "" ] && echo $usage && exit
[ "${my_zfstm_user}" = "" ] && echo $usage && exit

if [ ! "$my_zfstm_user" = `id -nu` ]; then
   echo "ERROR: Not running as the right backup user"
   exit
fi

zfs_name=`/sbin/zfs list -H -o name ${my_zfs} 2> /dev/null`

calc_usedbysnapshots_bytesize () {
  usedbysnapshots_bytesize=`/sbin/zfs list -H -o usedbysnapshots ${my_zfs}|tr GMKBWX gmkbwx|sed -Ees:g:km:g -es:m:kk:g -es:k:"*2b":g -es:b:"*128w":g -es:w:"*4 ":g -e"s:(^|[^0-9])0x:\1\0X:g" -ey:x:"*":|bc |sed "s:\.[0-9]*$::g"`
}

cleanup_snapshots () {
  _local_usedbysnapshots_limit=`echo "${local_usedbysnapshots_limit}"|tr GMKBWX gmkbwx|sed -Ees:g:km:g -es:m:kk:g -es:k:"*2b":g -es:b:"*128w":g -es:w:"*4 ":g -e"s:(^|[^0-9])0x:\1\0X:g" -ey:x:"*":|bc |sed "s:\.[0-9]*$::g"`
  calc_usedbysnapshots_bytesize
  while [ "$usedbysnapshots_bytesize" -gt "$_local_usedbysnapshots_limit" ]; do
    _delete=`/sbin/zfs list -H -o name -t snapshot -r ${my_zfs} | grep ${my_zfs}'@' | head -n1`
    /sbin/zfs destroy ${_delete}
    calc_usedbysnapshots_bytesize
  done
}

if [ "$zfs_name" = "$my_zfs" ]; then
  /sbin/zfs snapshot -r ${my_zfs}@${date}

  if [ "${local_snapshotsize_limit}" ]; then
    cleanup_snapshots
  fi
fi
